import 'dart:ffi';

import 'package:campus_mobile_experimental/core/providers/map.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class LocationsList extends StatelessWidget {
  final String destination;

  const LocationsList({
    Key? key,
    required this.destination,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final List<String> autocompleteSugesstions =
        generateAutocompleteSuggestions();

    return Flexible(
      child: Card(
        margin: EdgeInsets.all(5),
        child: ListView.separated(
          separatorBuilder: (context, index) => Divider(height: 0),
          itemCount: autocompleteSugesstions.length,
          shrinkWrap: true,
          itemBuilder: (context, index) {
            return ListTile(
              contentPadding: EdgeInsets.symmetric(horizontal: 15, vertical: 0),
              leading: Icon(Icons.location_pin),
              title: Text(autocompleteSugesstions[index]),
              onTap: () {
                Provider.of<MapsDataProvider>(context, listen: false)
                    .searchBarController
                    .text = autocompleteSugesstions[index];
                Provider.of<MapsDataProvider>(context, listen: false)
                    .fetchLocations();
                Navigator.pop(context);
              },
            );
          },
        ),
      ),
    );
  }

  List<String> generateAutocompleteSuggestions() {
    return locations
        .where((str) => str.toLowerCase().contains(
            destination.toLowerCase())) // maybe also check if it's a substring?
        .toList();
  }
}

final List<String> locations = [
  "The Food Co-op",
  "Single Occupancy Bathroom - Radiation Oncology PET/CT Center",
  "7201 Convoy Ct",
  "7197 Convoy Ct",
  "7198 Convoy Ct",
  "6711 Convoy Ct",
  "6809 Convoy Ct",
  "7187 Convoy Ct",
  "9610 Ridgehaven Ct",
  "3252 Holiday Ct",
  "7071 Convoy Ct",
  "3366 N Torrey Pines Ct",
  "Canyonview Aquatics and Activities Center (CANY)",
  "Washington, DC",
  "2159 Avenida De La Playa",
  "Movimiento Estudiantil Chicanola de Aztlan",
  "5855 Copley Dr",
  "5440 Morehouse Dr",
  "UNEX/Greenwich Dr",
  "4520 Executive Dr",
  "4570 Executive Dr",
  "4510 Executive Dr",
  "3655 Nobel Dr",
  "8950 Villa La Jolla Dr",
  "8939 VLJ Dr/IMG",
  "16766 Bernardo Center Dr",
  "8939 Villa La Jolla Dr SOM/Psych",
  "UCSD Medical Group - Acct Department (8575 Gibbs Dr)",
  "UCSD Medical Group - Acct Department (8665 Gibbs Dr)",
  "El Centro",
  "Marine EM Lab",
  "Fed Ex",
  "Fed Ex Dropbox",
  "Fed Ex Drop Box",
  "Fed Ex Drop box",
  "Thornton Hospital - 3rd Fl",
  "Galbraith Hall (GH)",
  "Hydration Location - Galbraith Hall (GH)",
  "GH Conference Room 134B",
  "GH Conference Room 135",
  "GH Conference Room 144",
  "GH Conference Room 174",
  "GH Conference Room 203",
  "GH Conference Room 243",
  "GH Conference Room 323A",
  "GL-SSH Library Computer Lab",
  "GL-Arts Library Computer Lab",
  "Hi Thai",
  "International Education Office",
  "International Center",
  "International Students and Programs Office (ISPO)",
  "Biomedical Research Facility II (BRF II)",
  "Engineering Building Unit II (EBU2)",
  "Biomedical Research Facility II",
  "Engineering Building Unit II",
  "Single Occupancy Bathroom - Engineering Building - Unit II",
  "Hydration Location - Engineering Building Unit II (EBU2)",
  "Biomedical Research Facility II (BFR 2) Lactation room",
  "The Village at Torrey Pines East #3",
  "The Village at Torrey Pines East #1",
  "The Village at Torrey Pines East #2",
  "The Village at Torrey Pines East #5",
  "The Village at Torrey Pines East #4",
  "Stryker Chair - The Village at Torrey Pines East #1",
  "The Village at Torrey Pines East #6",
  "Institutional Research",
  "School of Global Policy and Strategy (GPS) - Administration",
  "School of Global Policy and Strategy (GPS)",
  "School of Global Policy and Strategy (GPS)  - Library",
  "Robinson Library",
  "Robinson Administration",
  "GPS Student Affairs",
  "School of Global Policy and Strategy (GPS) - Auditorium",
  "Robinson Auditorium",
  "GPS Dean's Office",
  "Elizabeth \"Libby\" Gardner Room",
  "Single Occupancy Bathroom - School of Global Policy and Strategy (GPS)  - Administration",
  "Stryker Chair - La Jolla Del Sol",
  "La Jolla Del Sol 3383",
  "La Jolla Del Sol 3353",
  "La Jolla Del Sol 3359",
  "La Jolla Del Sol 3355",
  "La Jolla Del Sol 3357",
  "La Jolla Del Sol 3363",
  "La Jolla Del Sol 3365",
  "La Jolla Del Sol 3367",
  "La Jolla Del Sol 3371",
  "La Jolla Del Sol 3373",
  "La Jolla Del Sol 3381",
  "La Jolla Del Sol 8042",
  "La Jolla Del Sol 3389",
  "La Jolla Del Sol 3391",
  "La Jolla Del Sol 3393",
  "La Jolla Del Sol 3395",
  "La Jolla Del Sol 8006",
  "La Jolla Del Sol 8018",
  "La Jolla Del Sol 8030",
  "La Jolla Del Sol 8282",
  "La Jolla Del Sol 8046",
  "La Jolla Del Sol 8054",
  "La Jolla Del Sol 8066",
  "La Jolla Del Sol 8078",
  "La Jolla Del Sol 8090",
  "La Jolla Del Sol 8098",
  "La Jolla Del Sol 8114",
  "La Jolla Del Sol 8126",
  "La Jolla Del Sol 8138",
  "La Jolla Del Sol 8150",
  "La Jolla Del Sol 8162",
  "La Jolla Del Sol 8174",
  "La Jolla Del Sol 8186",
  "La Jolla Del Sol 8190",
  "La Jolla Del Sol 8202",
  "La Jolla Del Sol 8212",
  "La Jolla Del Sol 8222",
  "La Jolla Del Sol 8232",
  "La Jolla Del Sol 8242",
  "La Jolla Del Sol 8252",
  "La Jolla Del Sol 8272",
  "HDH Emergency Container - La Jolla Del Sol",
  "La Opinion",
  "La Jolla Playhouse",
  "Chipotle (La Jolla)",
  "La Jolla Village Drive / Villa La Jolla Drive",
  "8929 University Center Ln",
  "8899 University Center Ln",
  "Scripps Clinic La Jolla Ob/Gyn",
  "Price Center",
  "Hydration Location - Price Center West Hallway Entrance",
  "PH Conference Room 3501",
  "PH Conference Room 4502",
  "PH Conference Room 1115",
  "PH Conference Room 1130A",
  "PH Conference Room 2130",
  "PH Conference Room 3500",
  "PH Conference Room 3502",
  "PH Conference Room 4500",
  "PH Conference Room 4501",
  "Alpha Pi Omega",
  "Delta Sigma Pi",
  "6535 Alvarado Rd",
  "4150 Regents Rd",
  "7425 Mission Valley Rd",
  "11388 Sorrento Valley Rd",
  "1200 Garden View Rd",
  "3300 Old Mramar Rd/Warren Apts",
  "Revelle: Meteor Hall",
  "Revelle: Discovery Hall",
  "Revelle: Challenger Hall",
  "Revelle: Blake Hall",
  "Revelle: Beagle Hall",
  "Revelle: Atlantis Hall",
  "Revelle: Argo Hall",
  "Revelle 1 Residence Halls",
  "Hydration Location - Revelle Blake Hall",
  "Rita L. Atkinson Residences - Graduate Housing (RIAT)",
  "Stryker Chair - Rita L. Atkinson Residences - Graduate Housing (RIAT)",
  "Coral Conference Rm",
  "Lycan Conference Rm 1-125",
  "SDG&E Conference Rm 3-102",
  "Torrey Pines Conference Rm 1-308",
  "Triton Conference Rm 2-068",
  "Trout Conference Rm 1-504",
  "Building 9320, Conference Rm 211 (Modular 3)",
  "Department of Structural Engineering",
  "3510 Dunhill St",
  "4185 Front St",
  "7835 Trade St",
  "1899 McKee St",
  "4109 Front St",
  "402 Dickinson St/MPF",
  "410 Dickinson St/MRI",
  "408 Dickinson St/MPF",
  "220 Dickinson St/TGF",
  "132 West Dickinson St",
  "Medical Offices 4th & Lewis - 330 Lewis St",
  "Yo Lin Su Conference Room",
  "UCSD TV",
  "University Center 104 (U104)",
  "University Center 107",
  "University Center 108 (U108)",
  "University Center 109",
  "University Center 111",
  "University Center 112",
  "University Center 106",
  "University Center 110",
  "University Center 105",
  "UC San Diego Guardian",
  "UC San Diego Alumni Association",
  "UC San Diego Catering",
  "UC San Diego Radiation Oncology",
  "UC San Diego Bookstore",
  "Study Abroad UC San Diego",
  "UC San Diego Autism Center of Excellence",
  "UC San Diego Extension Business Services",
  "UC San Diego Extension Computer Labs",
  "UC San Diego Extension Dean's Office",
  "UC San Diego Extension Student Services",
  "UC San Diego Graduate Student Association",
  "UC San Diego Radiology Imaging Laboratory",
  "UC San Diego Research Center (URC)",
  "University Center 201 (U201)",
  "University Center 965 (U965)",
  "University Center 302 (U302)",
  "University Center 413 (U413)",
  "University Center 413A (U413A)",
  "University Center 303 (U303)",
  "University Center 409 (U409)",
  "University Center 400 (U400)",
  "Public Health Undergraduate Student Affairs Office (U202)",
  "Single Occupancy Bathroom - University Center 409 (U409)",
  "Single Occupancy Bathroom - UCTR 400 (U400)",
  "Single Occupancy Bathroom - UCTR 401 (U401)",
  "Single Occupancy Bathroom - University Center 302 (U302)",
  "Single Occupancy Bathroom - University Center 303 (U303)",
  "Single Occupancy Bathroom - University Center 611 (U611)",
  "Third Single UG Apartments",
  "Warren Single UG Apartments",
  "Pepper Canyon Single UG Apartments",
  "Center for US-Mexican Studies",
  "Southwest Fisheries Science Center (U.S. Government)",
  "Union Tribune Newspaper",
  "VA Medical Center",
  "Volunteer Connection",
  "Clive WJ Granger Seminar Room",
  "W.M. Keck Building (KECK)",
  "Single Occupancy Bathroom - W.M. Keck Building (KECK)",
  "ACS Computer Lab (WLH 2120)",
  "ACS Computer Lab (WLH 2124)",
  "ACS Computer Lab (CENTR 315)",
  "ACS Computer Lab (WLH 2126)",
  "ACS Computer Lab (WLH 2133)",
  "ACS Computer Lab (WLH 2211)",
  "ACS Computer Lab (WLH 2214)",
  "ACS Computer Lab (WLH 2216)",
  "ACS Computer Lab (WLH 2217)",
  "ACS Computer Lab (WLH 2218)",
  "ACS Computer Lab (EBU1 3329)",
  "ACS Computer Lab (EBU1 4515)",
  "ACS Computer Lab (EBU1 5702)",
  "ACS Computer Lab (EBU1 B552)",
  "ACS Computer Lab (PFBH 108)",
  "ACS Computer Lab (PFBH 161)",
  "ACS Computer Lab (U409 134)",
  "ACS Computer Lab (EBU1 4307)",
  "ACS Computer Lab (EBU3B 220)",
  "ACS Computer Lab (EBU3B 230)",
  "ACS Computer Lab (EBU3B 240)",
  "ACS Computer Lab (EBU3B 250)",
  "ACS Computer Lab (EBU3B 260)",
  "ACS Computer Lab (EBU3B 270)",
  "ACS Computer Lab (EBU3A 108)",
  "ACS Computer Lab (EBU3A 161)",
  "ACS Computer Lab (PCYNH 240)",
  "ACS Computer Lab (PCYNH 264)",
  "ACS Computer Lab (PCYNH 440)",
  "ACS Computer Lab (Geisel S&E)",
  "ACS Computer Lab (Geisel 137)",
  "ACS Computer Lab (U201 230)",
  "ACS Computer Lab (EBU3B 210)",
  "ACS Computer Lab (Geisel 2095)",
  "ACS Computer Lab (EBU2 203)",
  "ACS Computer Lab (EBU2 205)",
  "ACS Computer Lab (EBU2 239)",
  "ACS Computer Lab (EBU2 329)",
  "ACS Computer Lab (EBU2 330A)",
  "ACS Computer Lab (EBU2 330B)",
  "ACS Computer Lab (EBU2 335)",
  "ACS Computer Lab (EBU2 336)",
  "ACS Computer Lab (EBU2 337)",
  "ACS Computer Lab (EBU2 333A)",
  "ACS Computer Lab (EBU2B 035)",
  "ACS Computer Lab (EBU2 126)",
  "ACS Computer Lab (EBU2 312)",
  "Administrative Computing & Telecommunications",
  "ACT Help Desk",
  "ACT Campus Web Office",
  "TPCS, ACT Telecom Conference Room 255",
  "TPCS, ACT Telecom Conference Room 295",
  "Automated External Defibrillator - Campus Services Complex",
  "Automated External Defibrillator - Warren",
  "Automated External Defibrillator - University Center",
  "Automated External Defibrillator - Trade Street",
  "Automated External Defibrillator - Theatre District",
  "Automated External Defibrillator - Sorrento Valley",
  "Automated External Defibrillator - Sixth College",
  "Automated External Defibrillator - Sixth",
  "Automated External Defibrillator - Scripps",
  "Automated External Defibrillator - School of Medicine",
  "Automated External Defibrillator - Revelle",
  "Automated External Defibrillator - North Campus",
  "Automated External Defibrillator - Muir",
  "Automated External Defibrillator - Marshall",
  "Automated External Defibrillator - ERC",
  "Automated External Defibrillator - Shiley Eye Institute",
  "Admissions and Enrollment Services",
  "Financial Aid Office",
  "Academic Intership Program",
  "Applied Physics and Mathematics (APM)",
  "Kavli Institute for Brain and Mind (APM 1882)",
  "Center for Computational Mathematics",
  "Experimental Syntax Lab (AP&M 2432)",
  "Single Occupancy Bathroom - Applied Physics and Mathematics Building",
  "Auxiliary and Physical Plant Services",
  "The Art of Espresso",
  "University Art Gallery",
  "Stuart Art Collection Administration",
  "Chase Bank ATM",
  "Bank of America ATM",
  "Wells Fargo Bank ATM",
  "USE Credit Union ATM",
  "AVC Student Life",
  "4076 3rd Ave",
  "9333 Genesee Ave",
  "4094 Fourth Ave",
  "4305 University Ave",
  "2258 Island Ave",
  "3900 5th Ave",
  "3500 5th Ave/Psych/Med",
  "3500 5th Ave/Transplant",
  "Hydration Location - The Soap Bar",
  "High Bay Physics Laboratory",
  "Aquatic Center, Mission Bay",
  "Jacobs Medical Center - Bed Tower",
  "Biology Building (BIO)",
  "BIO Conference Room 1103",
  "BIO Conference Room 1129",
  "BIO Conference Room 1208",
  "Hydration Location - Bio Medical Library",
  "Biology Computer Labs (BONNER-1329)",
  "Biology Computer Labs (BONNER-1309)",
  "Biology Computer Labs (BONNER-1413)",
  "Biology Computer Labs (BONNER-1449)",
  "USPS collection box",
  "USPS Collection Box",
  "USPS Mail Box",
  "UPS Drop Box",
  "USPS Drop Box",
  "USPS Mail Collection Box",
  "Price Center Box Office",
  "The Black Resource Center (BRC)",
  "Biomedical Sciences Building/Basic Sciences Building (BSB)",
  "Office of the Vice Chancellor of Health Sciences",
  "BSB 1214",
  "BSB 1216",
  "BSB 2000",
  "BSB 2016",
  "Single Occupancy Bathroom - Biomedical Science Building",
  "Cashiers Office",
  "Center for Atmospheric Sciences",
  "Cross Cultural Center (CCC)",
  "Single Occupancy Bathroom - Cross Cultural Center (CCC)",
  "Center for Coastal Studies (CCS)",
  "Single Occupancy Bathroom - Center for Coastal Studies (CCS)",
  "Center for Energy Research",
  "Che Cafe",
  "Che Cafe Collective",
  "Che Cafe: North Side",
  "Che Cafe: South Side",
  "Community Law Project",
  "Center for Neural Circuits and Behavior (CNCB)",
  "Cognitive Neuroscience Laboratory",
  "Center for Networked System",
  "ACS Computer Lab (CRB 343)",
  "Center for Neural Computation",
  "Social Sciences Research Building",
  "Single Occupancy Bathroom - Clinical Research Facility",
  "Center For Research in Language",
  "Center for Research in Language",
  "Cambodian Student Association",
  "Cognitive Science Building (CSB)",
  "Cognitive Science (CSB) Computer Labs (CSB-115)",
  "Career Services Center (CSC)",
  "COVID Test Kits: Outdoor | CSC",
  "Campus Services Complex Trailer",
  "Single Occupancy Bathroom - Campus Services Complex, Building B (Police Department)",
  "Single Occupancy Bathroom - Campus Services Complex, Building D",
  "Single Occupancy Bathroom - UCSD Career Services Center",
  "Department of Computer Science and Engineering",
  "CSE Auditorium",
  "Center for Teaching Development",
  "Cartilage Tissue Engineering Laboratory",
  "CTF Hillcrest Lactation room",
  "Englekirk Ctr",
  "8899 University Ctr Lane/Radiology",
  "8899 University Ctr Lane",
  "ERC Student Activity Ctr",
  "Central Unit Library (CUL)",
  "Central Utilities Plant (CUP)/East",
  "Central Utilities Plant (CUP)",
  "3465 Camino Del Rio/S",
  "Single Occupancy Bathroom - T-42 SIO Storehouse in Marine Sciences Dev Center",
  "DHL",
  "Dimensions of Culture Program Offices",
  "Deep Sea Drilling East (DSD)",
  "Deep Sea Drilling West (DSD)",
  "Department of Electrical and Computer Engineering",
  "Department of Education Studies",
  "Environmental Management Facility",
  "Single Occupancy Bathroom (Staff Restrooms) - Hillcrest Inpatient Tower, 1st Floor, North End of South Wing",
  "Single Occupancy Bathroom (Staff Restrooms) - Hillcrest Inpatient Tower, 1st Floor, South End of South Wing",
  "ERC Administration North",
  "ERC Administration South",
  "Single Occupancy Bathroom - ERC Laundry",
  "ERC: Oceania Hall",
  "ERC: Kathmandu House",
  "ERC: Geneva Hall",
  "ERC: Asia Hall",
  "ERC Laundry South",
  "ERC: Africa Hall",
  "ERC: Cuzco House",
  "ERC: Europe Hall",
  "ERC Conference Room",
  "ERC: Earth South Hall",
  "ERC: Earth North Hall",
  "ERC: Asante House (ASANT)",
  "ERC: Fifth College Residence Halls",
  "ERC Conference Room North 123C",
  "ERC North Conference Room 123",
  "ERC North Conference Room 123A",
  "ERC North Conference Room 123B",
  "ERC: Latin America Hall",
  "ERC: Mesa Verde Hall",
  "ERC: Middle East Hall",
  "ERC: North America Hall",
  "Hydration Location - ERC POP Offices",
  "Hydration Location - ERC Great Hall",
  "Hydration Location - ERC East Upper Laundry Room",
  "Engineering Student Services",
  "Single Occupancy Bathroom - Ratner Children's Eye Center",
  "Shiley Eye Institute",
  "Abraham Ratner Children's Eye Center",
  "Anne Ratner Children's Eye Center",
  "Mesa Housing 3775 West",
  "Mesa Housing 3765 West",
  "Mesa Housing 3745 West",
  "Mesa Housing 3735 West",
  "Mesa Housing 3725 West",
  "Mesa Housing 3755 West",
  "Mesa Housing 3715 West",
  "WARREN APTS. - CENTRAL FAC. BLDG",
  "UCSD Medical Center Hillcrest-1st Flr",
  "UCSD Medical Center Hillcrest-2nd Flr",
  "UCSD Medical Center Hillcrest-3rd Flr",
  "UCSD Medical Center Hillcrest-4th Flr",
  "UCSD Medical Center Hillcrest-5th Flr",
  "UCSD Medical Center Hillcrest-6th Flr",
  "UCSD Medical Center Hillcrest-7th Flr",
  "UCSD Medical Center Hillcrest-8th Flr",
  "UCSD Medical Center Hillcrest-9th Flr",
  "UCSD Medical Center Hillcrest-10th Flr",
  "UCSD Medical Center Hillcrest-11th Flr",
  "Thornton Hospital - Flr 2",
  "Lesbian Gay Bisexual Transgender (LGBT) Resource Center",
  "Administrative: Lesbian Gay Bisexual Transgender (LGBT) Resource Center",
  "Geologic Data Center Archives",
  "Gary \"Gnu\" Tillman Memorial",
  "Sun God Lounge",
  "Sun God, 1983",
  "George Palade Laboratories (GPL)/Cellular and Molecular Medicine West(CMMW)",
  "Mobley Lab",
  "Graduate Student Association",
  "GSA Lounge",
  "Main Gym",
  "Hydration Location - Main Gym",
  "Rec Gym",
  "HDH Emergency Container - RIMAC",
  "HDH Emergency Container - Student Health",
  "HDH Emergency Container - Eucalyptus Point",
  "HDH Emergency Container - ECEC",
  "HDH Emergency Container - Glider Port",
  "HDH Emergency Container - Mesa Housing",
  "HDH Emergency Container - Sixth College",
  "HDH Emergency Container - Warren Res",
  "HDH Emergency Container - Coast Apartments",
  "HDH Emergency Container - Pit/School Of Pharmacy",
  "HDH Emergency Container - Revelle/Galbraith Hall",
  "HDH Emergency Container - SIO/Deep Sea Drilling",
  "HDH Emergency Container - Track/Spanos Training Center",
  "HDH Emergency Container - Canyon View Pool",
  "HDH Emergency Container - UCSD Media/Visual Arts",
  "HDH Emergency Container - East Parking Lot",
  "HDH Emergency Container - Muir Tennis Courts",
  "HDH Emergency Container - Goldberg Hall/Warren",
  "HDH Emergency Container - Gilman Parking Structure",
  "Humanities and Social Sciences Building (HSS)",
  "Single Occupancy Bathroom - Humanities and Social Sciences Building (HSS)",
  "Humanities and Social Sciences Computer Lab (HSS-6033)",
  "ICE Sat Lab",
  "Ida and Cecil Green Faculty Club",
  "Interfraternity Council",
  "Robert F Engle III Seminar Room",
  "School of Medicine Building 2",
  "Internal Medicine Group (IMG)",
  "Cancer Research Center, IMG, Building 1",
  "Institute of Neural Cognition",
  "Institute of the Americas Building (IOA)",
  "IOA Addition Conference Room 133",
  "IOA Addition Conference Room 218",
  "IOA Conference Room 112",
  "IOA Conference Room 203",
  "IOA Conference Room 215",
  "Single Occupancy Bathroom - Institute of the Americas Building (IOA)",
  "Institute of the Americas Building Addition",
  "Intergroup Relations Program",
  "Ivy Building",
  "Single Occupancy Bathroom - Ivy",
  "Jai by Wolfgang Puck",
  "Jacobs Medical Center (JMC)",
  "RIMAC Annex Computer Lab",
  "GL-2095 Computer Lab",
  "Single Occupancy Bathroom - Kaplan Lab (Experimental Aquarium)",
  "OBM Lab",
  "Surgery Research Lab",
  "Diabetes Research Lab",
  "Experimental Phycology Lab",
  "Magnetic Properties Lab",
  "Muscle Physiology Lab",
  "GL-1001 Computer Lab",
  "GL-2098 Computer Lab",
  "GL-137 computer lab",
  "SUNGOD Computer Lab",
  "Communication Computer Lab",
  "Computer Lab (ECON 200 Grad Lab)",
  "Powell Structural Systems Lab",
  "ACS Computer Lab (AP&M 2402A)",
  "SDSC Training Lab 279",
  "ACS Computer Lab (Sequoyah 142)",
  "ACS Computer Lab (24hr Lounge)",
  "Literature Building (LIT)",
  "Department of Literature",
  "LIT Conference Room 411",
  "LIT Conference Room 155",
  "LIT Conference Room 217",
  "LIT Conference Room 237",
  "LIT Conference Room 311",
  "LIT Conference Room 355",
  "LIT Conference Room 437",
  "LIT Conference Room 455",
  "Los Angeles Area",
  "Los Angeles Times",
  "Los Angeles Room",
  "Thurgood Marshall Room (formerly Santa Barbara / Los Angeles Room)",
  "Lot P003",
  "Lot P701",
  "Lot P704",
  "Lot P702",
  "Lot P703",
  "Lot P759",
  "Parking Lot P303",
  "Parking Lot P413",
  "Parking Lot P017",
  "Parking Lot P002",
  "Parking Lot P006",
  "Parking Lot P008",
  "Parking Lot P010",
  "Parking Lot P012",
  "Parking Lot P004",
  "Parking Lot P013",
  "Parking Lot P014",
  "Parking Lot P015",
  "Parking Lot P105",
  "Parking Lot P107",
  "Parking Lot P108",
  "Parking Lot P110",
  "Parking Lot P112",
  "Parking Lot P114",
  "Parking Lot P203",
  "Department of Mechanical and Aerospace Engineering",
  "MAN Conference Room 212",
  "MAN Conference Room B124",
  "MAN Computer Lab (B114)",
  "MAN Computer Lab (B206)",
  "Marine Biology Building",
  "Moores UCSD Cancer Center (MCC)",
  "Stryker Chair - Moores UCSD Cancer Center (MCC)",
  "Communication Building",
  "Single Occupancy Bathroom - Moores Cancer Center",
  "McGill Hall Annex (MCG-A)",
  "Multicultural Greeks",
  "Medical Center Modular Building 1 (MCM1)",
  "Medical Center Modular Building 2 (MCM2)",
  "Club Med",
  "Medical Education Office",
  "Medical Education and Telemedicine",
  "Multipurpose Facility",
  "MPF Conference Room 134",
  "MPF Conference Room 177",
  "MPF Conference Room 191",
  "MPF Conference Room 222",
  "MPF Conference Room 256",
  "MPF Conference Room 369",
  "MPF Conference Room 450",
  "MPF Conference Room 483",
  "MPF Conference Room L013-2",
  "MPF Conference Room L034",
  "MPF Conference Room L064",
  "Marine Physical Laboratory",
  "410 Dickinson/MRI",
  "Center for Functional Magnetic Resonance Imaging (MRI)",
  "Robert N. Berk Magnetic Resonance Institute",
  "Magnetic Resonance Imaging (MRI)",
  "MTF Conference Room 111",
  "MTF Conference Room 175",
  "MTF Conference Room 211",
  "MTF Conference Room 249",
  "MTF Conference Room 311",
  "MTF Conference Room 349",
  "MTF Conference Room 411",
  "MTF Conference Room 449",
  "The Center for the Future of Surgery",
  "Family and Preventive Medicine",
  "Medical Teaching Facility",
  "Hydration Location - Medical Teaching Facility",
  "Mayer Hall Addition (MYR-A)",
  "New Yorker Newspaper",
  "New Scripps Building (SCRPS)",
  "New York Times Newspaper",
  "New York Time Newspaper",
  "Center for NMR Spectroscopy and Imaging of Proteins (Bubble Building)",
  "Natural Sciences Building (NSB)",
  "Natural Sciences Computer Lab (NSB-1103A)",
  "Natural Sciences Computer Lab (NSB-1111)",
  "Natural Sciences Computer Lab (NSB-1303A)",
  "Natural Sciences Computer Lab (NSB-1313A)",
  "Natural Sciences Computer Lab (NSB-2303)",
  "Natural Sciences Computer Lab (NSB-2311)",
  "Natural Sciences Computer Lab (NSB-2319)",
  "NSB Conference Room 1205",
  "NSB Conference Room 3209",
  "NSB Conference Room 3211",
  "NSB Conference Room 4209",
  "NSB Conference Room 4211",
  "NSB Conference Room 6203",
  "Nikkei Student Union",
  "Nierenberg Hall Annex (NTV Building)",
  "Single Occupancy Bathroom - Nierenberg Hall Annex (NTV Building)",
  "Keck Oceanographic and Atmospheric Research - 1  (OAR)",
  "Keck Oceanographic and Atmospheric Research - 2 (OAR)",
  "Keck Oceanographic and Atmospheric Research - 3  (OAR)",
  "Single Occupancy Bathroom - Keck OAR 1",
  "Single Occupancy Bathroom - Keck OAR 2",
  "Keck Center for Oceanographic and Atmospheric Research",
  "Ocean Drilling Program",
  "Old Director's House",
  "Old Town Plaza",
  "Warren Old Apartments Building 1-4",
  "Old Town Transit Center",
  "George H. Scripps Building (Old Scripps Building)",
  "Single Occupancy Bathroom - T-16/SIO Old Director's House",
  "Cafe Ole",
  "One Stop",
  "One Earth One Justice",
  "One Miramar Street",
  "One Miramar Street Building 1",
  "One Miramar Street Building 2",
  "One Miramar Street Building 3",
  "One Miramar Street Building 4",
  "One Miramar Street Building 5",
  "COVID Test Kits: Outdoor | One Miramar",
  "Office for Students with Disabilities",
  "OceanView Terrace",
  "Hydration Location - OceanView Terrace",
  "Pay phone",
  "Price Center East",
  "Stryker Chair - Price Center East",
  "Hydration Location - Price Center East 4th floor next to elevator",
  "Pre-Dental Society",
  "Pep Band",
  "Panhiellenic Association",
  "Delta Lambda Phi",
  "Phi Delta Epsilon",
  "Campus Services Complex - Electric Shops",
  "T-40 Driving Locker, PPS Services",
  "Skaggs Pharmaceutical Sciences Building (PSB)",
  "Powell Structures and Components Laboratory",
  "Porter's Pub and Stage",
  "Student Center, Stage @ the Pub",
  "Hydration Location - Porter's Pub",
  "Robinson Building Complex (RBC)",
  "Roger's Community Garden",
  "Red Shoe, 1996",
  "Red Shoe Room (formerly Gallery B)",
  "TMC Office of Res Life",
  "Hydration Location - Marshall Building P Res Hall",
  "Hydration Location - Marshall Building Q Res Hall",
  "Hydration Location - Marshall Building V Res Hall",
  "Hydration Location - TMC Office of Res Life",
  "Hydration Location - Warren Res Life Office",
  "Revelle: Keeling Apartments",
  "Raza Resource Centro",
  "UCSD Student Run Television (SRTV)",
  "Sam and Rose Stein Institute for research on aging",
  "San Quentin",
  "Single Occupancy Bathroom - San Diego Supercomputer Center",
  "San Francisco Room",
  "San Diego Writing Project",
  "Math for America San Diego",
  "San Diego State University (SDSU)",
  "San Diego Supercomputer Center (SDSC)",
  "San Francisco/Santa Cruz Room",
  "San Diego Supercomputer East Expansion",
  "San Diego Supercomputer Center Addition (SDSC)",
  "San Diego National Bank Conference Room",
  "Eleanor Roosevelt (formerly San Francisco / Santa Cruz room)",
  "Student Financial Solutions",
  "Society for Creative Anachronism, College of Saint Artemas",
  "Single Occupancy Bathroom - Deep Sea Drilling West",
  "Deep Sea Drilling West",
  "ACS Computer Lab (Price Center SGL)",
  "Student Health Advocates",
  "Student Health Services",
  "Stryker Chair - Student Health Services",
  "Single Occupancy Bathroom - SIO, Sumner Auditorium",
  "IGPP 3000 - Revelle Laboratory",
  "IGPP 1000 - Revelle Laboratory - 8795",
  "SIO Warehouse",
  "SIO, Sumner Auditorium",
  "SIO Director's Office",
  "T-42 SIO Storehouse",
  "SIO, Building T-29",
  "T-3 SIO Administrative Computing",
  "Scripps Institution of Oceanography (SIO)",
  "SIO Marine Biology Conference Room",
  "SIO Computer Lab (OSB-10)",
  "SIO Eckart Building Lactation room",
  "Hydration Location - SIO Administration Building",
  "COVID Test Kits: Outdoor | SIO",
  "Single Occupancy Bathroom - IGPP 2000",
  "Single Occupancy Bathroom - IGPP 3000 - Revelle Laboratory",
  "Single Occupancy Bathroom - IGPP Munk Laboratory",
  "Student Legal Services",
  "Structural and Materials Engineering",
  "ACS Computer Lab (SME-143)",
  "Structural and Material Engineering (SME) Lactation room",
  "Stein Clinical Research Building (SCRB)",
  "Single Occupancy Bathroom - School of Medicine Building 1",
  "Single Occupancy Bathroom - School of Medicine Building 2",
  "Single Occupancy Bathroom - School of Medicine Building 3",
  "Single Occupancy Bathroom - School of Medicine Building 4",
  "130 Dickinson/SRL",
  "Social Sciences Building (SSB)",
  "Social Sciences Computer Lab (SSB-139/140)",
  "Social Sciences Computer Facility",
  "Single Occupancy Bathroom - Social Sciences Building",
  "SSC Conference Room 260",
  "SSC Conference Room 300",
  "SSC Conference Room 360",
  "SSC Conference Room 400",
  "SSC Conference Room 450",
  "SSC Conference Room 554",
  "SSC Conference Room 554A",
  "Student Services Center",
  "Shipboard Technical Support",
  "Sun City",
  "Thurgood Marshall College Administration Building",
  "Tea and Home Plate Cafe",
  "Studio Ten 300",
  "Third College Lecture Hall Building",
  "Marshall: Apartment - F",
  "Marshall: Apartment - A",
  "Marshall: Apartment - B",
  "Marshall: Apartment - D",
  "Marshall: Apartment - E",
  "Marshall: Apartment - G",
  "Marshall: Apartment - H",
  "Marshall: Apartment - J",
  "Marshall: Apartment - K",
  "Marshall: Apartment - L",
  "Marshall: Apartment - M",
  "Marshall: Residence Hall N",
  "Marshall: Residence Hall O",
  "Marshall: Residence Hall P",
  "Marshall: Residence Hall Q",
  "Marshall: Residence Hall R",
  "Marshall: Residence Hall S",
  "Marshall: Residence Hall T",
  "Marshall: Residence Hall U",
  "Marshall: Residence Hall V",
  "TMC Tennis Court",
  "TMC Mail Boxes",
  "TMC Lower Apartments Laundry",
  "TMC Administration Conference Room 126",
  "TMC Administration Conference Room 127",
  "TMC Psychological and Counseling Services",
  "Torrey Pines Center North",
  "Training Center North - Torrey Pines Center North",
  "Two Running Violet V Forms, 1983",
  "University of California, Berkeley (UCB)",
  "University Events Office",
  "Undergrad Investment Society",
  "University Pacific Center (UPC)",
  "UPS",
  "Urey Hall Annex (URY-A)",
  "USA Today",
  "USA Today Newspaper",
  "Herbert F. York Undergraduate Sciences Building (USB)",
  "Visual Arts Facility (VAF)",
  "Visual Arts Facility (VIS)",
  "Willaim J. von Liebig Center",
  "Vietnamese Student Association",
  "6735 Gifford Way",
  "Coast Apartments: Expedition Way",
  "Expedition Way / North Torrey Pines Road",
  "North Torrey Pines Road / Expedition Way",
  "Naga Way / Vaughn Hall: East Side",
  "Naga Way / Vaughn Hall: West Side",
  "West Coast Repository",
  "Wells Fargo Hall (WFH)",
  "Why Not Here? Lounge",
  "Warren Lecture Hall (WLH)",
  "Arctic and Antarctic Research Center",
  "UREY ADDT Conference Room 2020",
  "UREY ADDT Conference Room 2060A",
  "Center for Aids Research/AIDS Research Institute",
  "Atmospheric Oxygen Research Group",
  "Asian Pacific Islander Student Alliance",
  "Warren Apts for Grads",
  "Village West Single Grad Apts",
  "Institute for International, Comparative, and Area Studies",
  "Ridgewalk at North Campus Recreation Area",
  "Muir College Athletic Area (MUAA)",
  "North Campus Athletic Area",
  "Single Occupancy Bathroom - Hillcrest Inpatient Tower, 1st Floor by Emergency Room Waiting Area",
  "Single Occupancy Bathroom - Hillcrest Inpatient Tower, 1st Floor by North Eastern Area",
  "Argo Hall",
  "Hydration Location - Argo Hall",
  "Single Occupancy Bathroom - Visual Arts Center",
  "Department of Visual Arts",
  "Visual Arts Facility - Building 4",
  "Center for Research in Computing and the Arts",
  "Visual Arts Facility - Building 5",
  "Asia Hall",
  "East Asia Collection",
  "Antiviral Research Center",
  "Volley Ball Court",
  "Marching Band",
  "Chase Bank",
  "Bear, 2005",
  "Bear Room (formerly Gallery A)",
  "Bike Shop",
  "Thornton Hospital - Modular Bldg 3",
  "Marine Sciences Development Center Bldg A",
  "Marine Sciences Development Center Bldg B",
  "Marine Science Development Center Bldg C",
  "Marine Sciences Development Center Bldg D",
  "Hydration Location - Blue Peppers",
  "9909 Mira Mesa Blvd",
  "Bonner Hall (BONN)",
  "Geisel Library Book Return",
  "Geisel Library Entrance Book Return",
  "Biomedical Library Breezeway North Book Return",
  "Biomedical Library Breezeway South Book Return",
  "Single Occupancy Bathroom - Cafe Ventanas",
  "Perks cafe",
  "Come On In! Cafe",
  "Crouton's Cafe",
  "Cafe Ventanas",
  "Daphne's Greek Cafe",
  "Come on In! Cafe Express",
  "Revelle Commons/Revelle Cafe",
  "Hydration Location - Cafe Ventanas",
  "Center for Advanced Laboratory Management",
  "Course and Professor Evaluations Office",
  "Counseling and Psychological Services",
  "Triton Card Accounts Services",
  "Children's Urgent Care",
  "Ambulatory Care Center",
  "Animal Care Program",
  "Perlman Ambulatory Care Center",
  "Perlman Ambulatory Care Unit",
  "Healthcare Administration Medical Director, Ambulatory and Primrary Care",
  "Fairbanks Coffee Cart",
  "Fairbank Coffee Cart",
  "Java Coast Coffee Cart",
  "Center for Astrophysics and Space Sciences",
  "Cellular and Molecular Medicine East (CCME)",
  "Palade Labs (CCMW)",
  "Cellular and Molecular Medicine West (CCMW)",
  "Core cell culture facility",
  "Sanford Consortium/Stem Cell Building",
  "Mesa Housing Laundry",
  "Mesa Housing 9228 Central",
  "Central Mesa Residential Apartments",
  "Mesa Housing 9230 Central",
  "Mesa Housing 9232 Central",
  "Mesa Housing 9242 Central",
  "Mesa Housing 9244 Central",
  "Mesa Housing 9240 Central",
  "Mesa Housing 9234 Central",
  "Mesa Housing 9236 Central",
  "Mesa Housing 9238 Central",
  "Mesa Housing 9246 Central",
  "Mesa Housing 9248 Central",
  "Mesa Housing 9252 Central",
  "Mesa Housing 9254 Central",
  "Mesa Housing 9250 Central",
  "Mesa Housing 9256 Central",
  "Mesa Housing 9260 Central",
  "Mesa Housing 9258 Central",
  "Mesa Housing 9264 Central",
  "Mesa Housing 9262 Central",
  "Mesa Housing 9268 Central",
  "Mesa Housing 9266 Central",
  "Mesa Housing 9270 Central",
  "Mesa Housing 9226 Central",
  "Single Occupancy Bathroom - Mesa Housing 9238 Central",
  "Single Occupancy Bathroom - Mesa Housing 9264 Central",
  "Copley International Conference Center (CICC)",
  "CICC Conference Room 109",
  "CIMS Conference Room",
  "Clinical Research Facility/Clinical Sciences Building (CLIN)",
  "Kalmia Clinical Trials Office",
  "Hawaiian Club",
  "Persian Club",
  "Faculty Club Lounge",
  "Faculty Club, Room 1",
  "Faculty Club, Room 2",
  "Faculty Club, Room 4",
  "Faculty Club, Room 5",
  "Center for Marine Biodiversity and Conservation",
  "CMME 2001",
  "CMME 2044",
  "CMME 2047",
  "CMME Conference Room 1080",
  "CMME Conference Room 2001",
  "CMME Conference Room 2047",
  "CMME Conference Room 3001",
  "CMME Conference Room 3045",
  "Single Occupancy Bathroom - Center for Molecular Medicine East (CMME)",
  "CMRR Auditorium",
  "Center for Magnetic Recording Research (CMRR)",
  "CMRR Conference Room 119",
  "CMRR Conference Room 121",
  "CMRR Conference Room 1H",
  "Center Hall (CENTR)",
  "Vending Machine (Coke)",
  "Indirect Cost Analyst",
  "Conrad Prebys Music Center (CPMC)",
  "Conrad Prebys Music Center Computer Labs (CPMC-201)",
  "Conrad Prebys Music Center Computer Labs (CPMC-204)",
  "Conrad Prebys Music Center Computer Labs (CPMC-205)",
  "Conrad Prebys Music Center Computer Labs (CPMC-206)",
  "Conrad Prebys Music Center Computer Labs (CPMC-207)",
  "Central Research Services Facility (CRSF)",
  "Phillips Vera Cruz Room",
  "Rady Children's Hospital-CSSD",
  "Altman CTRI Building",
  "Cups Coffee",
  "Canyon Vista Administration",
  "Computer Vision and Robotics Research Laboratory",
  "Dark Star",
  "UCSD Dark Room",
  "Broadband Seismic Data Collection Center",
  "Dean of Social Sciences",
  "Dean's Residence, Assistant, Sixth College",
  "International Center Dean's Office",
  "School of Medicine Dean's Office",
  "Hydration Location - Deep Seal Drilling West",
  "EDNA Help Desk",
  "T-25 Digital Imaging Analysis Laboratory",
  "The Dogg House",
  "Hydration Location - Sixth College Dogg House",
  "Half Dome Lounge",
  "Parking Lot P733 (Campus Point West Parking Structure, Bottom of Ramp Down from Street Level)",
  "Parking Lot P734 (Campus Point West Parking Structure, Bottom of Ramp Down from Street Level)",
  "Student Services Mail Drop (No USPS Mail)",
  "Earl's Place and Market",
  "Earl Warren Room",
  "Earl Warren College Administration",
  "Earl's Warren College Room",
  "Stryker Chair - Earl Warren College",
  "Tamarack apartments East",
  "Ballroom East",
  "Middle East Hall",
  "Tamarack Apartments East",
  "Asante House East",
  "Cuzco House East",
  "East Meeting Room",
  "IGPP: East Side",
  "Village East Apartments",
  "Hopkins Structure: East",
  "Parking Lot P721 (East Campus East Lower Level)",
  "Parking Lot P722 (East Campus East Upper Level)",
  "Eleanor Roosevelt College Laundry East",
  "Price Center East Expansion",
  "Cellular and Molecular Medicine East",
  "East Campus Office Building",
  "Peterson Hall: East Side",
  "Eleanor Roosevelt College: East Side",
  "Muir: Apartments - S House East",
  "Muir: Apartments - T House East",
  "Tuolumne Apartments - T House East",
  "Pangea Structure: East Side",
  "Warren Apartments: East Side",
  "The Village at Torrey Pines East #7",
  "330 East Lewis Street",
  "East Campus Office Building (ECOB)",
  "Parking Lot P751: East",
  "Muir Apartments: East Side",
  "ECOB Lactation room",
  "Economics Building (ECON)",
  "Economics Department Faculty Lounge",
  "Economics Department Student Services",
  "ACS Computer Lab (ECON 100)",
  "ACS Computer Lab (ECON 200)",
  "EDNA",
  "Eleanor Roosevelt Apartments",
  "Eleanor Roosevelt College Administration",
  "Stryker Chair - Eleanor Roosevelt College",
  "Eleanor Roosevelt College (ERCA 117)",
  "Roosevelt Residence Halls",
  "Ellie's Garden: The Farm",
  "Digital Audio and Film Reserves",
  "FLIP Research Vessel",
  "Fung Auditorium",
  "Birch Aquarium Gift Shop",
  "Basketball Half Court",
  "Tamarack Hall",
  "Spiess Hall (SPIES)",
  "Single Occupancy Bathroom - Black Hall",
  "Single Occupancy Bathroom - Spiess Hall",
  "Single Occupancy Bathroom - Powell-Focht Bioengineering Hall",
  "Single Occupancy Bathroom - Richard C. Atkinson Hall",
  "Great Hall",
  "Bates Hall",
  "Brown Hall",
  "Brennan Hall",
  "Douglas Hall",
  "Ritter Hall",
  "Isaacs Hall",
  "Sverdrup Hall",
  "Europe Hall",
  "Meteor Hall",
  "Sequoyah Hall",
  "Earth Hall",
  "Stewart Hall",
  "Frankfurter Hall",
  "Center Hall",
  "Otterson Hall",
  "Africa Hall",
  "Atlantis Hall",
  "Nierenberg Hall",
  "Black Hall",
  "Goldberg Hall",
  "Harlan Hall",
  "Atkinson Hall",
  "Galathea Hall",
  "Pacific Hall",
  "York Hall",
  "Mayer Hall",
  "Mandler Hall",
  "McGill Hall",
  "Hubbs Hall",
  "Bonner Hall",
  "Challenger Hall",
  "Thich Nhat Hanh Room",
  "Healthcare Otolaryngology/Head and Neck Surgery",
  "HEME House - Hemophilia Treatment Center",
  "International Cooperative Nursery School",
  "International Faculty & Scholar Office",
  "Institute on Global Conflict & Cooperation (IGCC)",
  "IGPP Reading Room",
  "IGPP 4000 - Revelle Laboratory - 8785",
  "IGPP Munk Lab - 8800",
  "IGPP 2000 - Revelle Laboratory",
  "IGPP Board Room",
  "IGPP Revelle Laboratory",
  "IGPP: West Side",
  "IGPP 1000 - Revelle Laboratory",
  "International House",
  "Student Info",
  "Institute for Nonlinear Science",
  "IPAS Conference Room",
  "Single Occupancy Bathroom - School of International Relations and Pacific Studies",
  "IWDC",
  "Joint Operation for Marine Observations",
  "Single Occupancy Bathroom - Hamilton Glaucoma and Joan and Irwin Jacobs Retina Center",
  "Hamilton Glaucoma and Joan and Irwin Jacobs Retina Center",
  "Irwin Mark and Joan Klein Jacobs Engineering Hall",
  "John's Place and Market",
  "John Muir College Room",
  "3525 John Hopkins Court",
  "John Muir College Administration",
  "Stryker Chair - John Muir College",
  "Rebecca and John Moores UCSD Cancer Center",
  "Keck Oceanographic and Atmospheric Research - 1",
  "Burger King",
  "Hydration Location - Burger King",
  "COVID Test Kits: Outdoor | Muir",
  "COVID Test Kits: Indoor | BRFII",
  "COVID Test Kits: Outdoor | Osler",
  "COVID Test Kits: Indoor | Marshall Lower",
  "COVID Test Kits: Outdoor | Nuevo East: Porton",
  "COVID Test Kits: Indoor | Price Center",
  "COVID Test Kits: Outdoor | Central Mesa",
  "KSDT radio",
  "Kaplan Labs",
  "East Village B6 Gallery Computer Labs",
  "Rupertus Lane",
  "Shuttle Stop at Gilman Drive and Mandeville Lane",
  "Gilman Drive / Mandeville Lane: South Side",
  "Gilman Drive / Mandeville Lane: North Side",
  "La Jolla Shores Drive / Inyaha Lane",
  "Gilman Drive / Osler Lane: East Side",
  "Gilman Drive / Osler Lane: West Side",
  "Gildred Latin American Studies Building",
  "Scripps Lawn",
  "Laboratory of Comparative Human Cognition",
  "Leichtag Family Foundation Biomedical Research Building",
  "LFFB Conference Room 2A19",
  "LFFB Conference Room 107",
  "LFFB Conference Room 205",
  "LFFB Conference Room 285",
  "LFFB Conference Room 2A05",
  "LFFB Conference Room 3A05",
  "LFFB Conference Room 405",
  "Single Occupancy Bathroom - Leichtag Family Foundation Biomedical Research Building",
  "Marine Life Research",
  "Student Life Business Operations",
  "The Loft",
  "Zanzibar at the Loft",
  "Single Occupancy Bathroom - Marine Physical Laboratory - Point Loma Building 4, Nimitz",
  "Marine Physical Laboratory - Point Loma Building 4",
  "Marine Physical Laboratory - Point Loma Building 106",
  "Marine Physical Laboratory - Point Loma Building 1",
  "Marine Physical Laboratory - Point Loma Building 3",
  "Marine Physical Laboratory - Point Loma Building 2",
  "Love 146",
  "Pulmonary Interim UCSD Lung Center",
  "Mail Center",
  "Mail Center and Offices",
  "UCSD Mail Services",
  "Fireside Lounge Mail Boxes",
  "Student Organization Mail Office and Workroom",
  "Mail Center Forms Management",
  "Main Gymnasium",
  "Media Services Main Offices",
  "Single Occupancy Bathroom (Staff Restrooms) - Hillcrest Inpatient Tower, 1st Floor, West of Main Tower",
  "Single Occupancy Bathroom (Staff Restrooms) - Hillcrest Inpatient Tower, Lower Level, East of Main Tower",
  "Single Occupancy Bathroom - Hillcrest Inpatient Tower, Lower level by Main Entrance Elevators",
  "Multi Asian Student Association",
  "Mayer Hall (MAYER)",
  "MAYER Computer Lab (MAYER-3229)",
  "MAYER Computer Lab (MAYER-2326)",
  "MAYER Computer Lab (MAYER-2306)",
  "MAYER Computer Lab (MAYER-2130)",
  "MAYER Computer Lab (MAYER-2544)",
  "MAYER Computer Lab (MAYER-2574)",
  "MAYER Computer Lab (MAYER-2722)",
  "MAYER Computer Lab (MAYER-3543)",
  "MAYER Computer Lab (MAYER-3544)",
  "MAYER Computer Lab (MAYER-3574)",
  "MAYER Computer Lab (MAYER-4623)",
  "MAYER Computer Lab (MAYER-2110)",
  "Molecular Biology Research Lab",
  "Single Occupancy Bathroom - Mesa Housing 3755 West",
  "Single Occupancy Bathroom - Mesa Housing 3875 North",
  "Single Occupancy Bathroom - Mesa Housing 3999 North",
  "Single Occupancy Bathroom - Mesa Housing 9126 South",
  "Single Occupancy Bathroom - Mesa Housing 9156 South",
  "Single Occupancy Bathroom - Mesa Housing 9184 South",
  "Mesa Apartments",
  "Mesa Housing",
  "UNEX/Sorrento Mesa",
  "South Mesa Housing",
  "Central Mesa Housing",
  "Mesa Housing 3903 North",
  "Mesa Housing 3911 North",
  "Mesa Housing 3919 North",
  "Mesa Housing 3927 North",
  "Mesa Housing 3943 North",
  "Mesa Housing 3935 North",
  "Mesa Housing 3951 North",
  "Mesa Housing 3959 North",
  "Mesa Housing 3967 North",
  "Mesa Housing 3983 North",
  "Mesa Housing 3975 North",
  "Mesa Housing 3999 North",
  "Mesa Housing 3991 North",
  "Mesa Housing 4043 North",
  "Mesa Housing 4059 North",
  "Mesa Housing 4051 North",
  "Mesa Housing 4075 North",
  "Mesa Housing 4067 North",
  "Mesa Housing 4091 North",
  "Mesa Housing 4099 North",
  "Mesa Housing 4083 North",
  "Muir Single Undergraduate Apartment",
  "Muir Laundry",
  "Middle of Muir",
  "Muir Writing Program",
  "Hydration Location - Muir",
  "Middle of Muir Store",
  "Muir Commons Annex",
  "Muir College Drive",
  "Muir: Apartments - S House Laundry",
  "Muir Commons Sequoia Room",
  "Muir College Residence Halls",
  "Muir Single Undergraduate Tamarack Apartments",
  "Muir: College Residence Hall Tioga",
  "Muir: Apartments - S House North",
  "Muir: Apartments - S House South",
  "Muir: Apartments - T House North",
  "Muir: Apartments - T House South",
  "Muir: Apartments - S House West",
  "Muir: Apartments -T House West",
  "Muir: College Residence Hall Tenaya",
  "Muir Woods Coffee House",
  "Muir Apartments: West Side",
  "Munk Room",
];
