#!/bin/bash
# Remove all .bak backup files generated by auto-fix scripts
# Usage:
#   ./scripts/cleanup_backups.sh
#   ./scripts/cleanup_backups.sh --dry-run  # Preview what would be deleted

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
cd "$repo_root"

DRY_RUN=false
if [[ "$1" == "--dry-run" ]]; then
    DRY_RUN=true
fi

echo "==============================="
echo "🧹 Cleaning up backup files"
echo "==============================="
echo

# Find all .bak files in the repository
backup_files=$(find . -name "*.bak" -type f 2>/dev/null || true)

if [[ -z "$backup_files" ]]; then
    echo "✅ No backup files found - repository is clean!"
    exit 0
fi

echo "Found the following backup files:"
echo "$backup_files" | while IFS= read -r file; do
    echo "  $file"
done

backup_count=$(echo "$backup_files" | wc -l)
echo
echo "Total backup files found: $backup_count"

if [[ "$DRY_RUN" == "true" ]]; then
    echo
    echo "DRY RUN MODE - No files will be deleted"
    echo "Run without --dry-run to actually remove these files"
    exit 0
fi

echo
read -p "Are you sure you want to delete all these backup files? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Cleanup cancelled"
    exit 1
fi

echo
echo "🗑️  Removing backup files..."

deleted_count=0
echo "$backup_files" | while IFS= read -r file; do
    if [[ -f "$file" ]]; then
        rm "$file"
        echo "  Deleted: $file"
        deleted_count=$((deleted_count + 1))
    fi
done

echo
echo "✅ Cleanup completed!"
echo "📊 Deleted $backup_count backup files"
echo "🎯 Repository is now clean of .bak files"
